version: '3.8'
services:
  server:
    container_name: server
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy_settings.conf:/etc/nginx/proxy_settings.conf:ro
      - ./nginx/cors_headers.conf:/etc/nginx/cors_headers.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      - api

  db:
    container_name: db
    image: mongo
    volumes:
      - /data-vol:/data/db

  api:
    container_name: api
    restart: always
    build: ./api
    environment:
      - PORT=8001

  apitwo:
    container_name: apitwo
    restart: always
    build: ./apitwo
    environment:
      - PORT=8002

  nuxt-app:
    build: ./trader_front
    container_name: nuxt-app
    restart: always
    environment:
      - PORT=4000
    command: 'npm run start'