const stocks = [
    { symbol: "AAPL", name: "Apple Inc.", image: "AAPL@2x.png" },
    { symbol: "AMD", name: "Advanced Micro Devices, Inc.", image: "AMD@2x.png" },
    { symbol: "T", name: "AT&T Inc.", image: "T@2x.png" },
    { symbol: "BAC", name: "Bank of America Corporation", image: "BAC@2x.png" },
    { symbol: "F", name: "Ford Motor Company", image: "F@2x.png" },
    { symbol: "GE", name: "General Electric Company", image: "GE@2x.png" },
    { symbol: "MSFT", name: "Microsoft Corporation", image: "MSFT@2x.png" },
    { symbol: "CCL", name: "Carnival Corporation & Plc", image: "CCL@2x.png" },
    { symbol: "PFE", name: "Pfizer Inc.", image: "PFE@2x.png" },
    { symbol: "WFC", name: "Wells Fargo & Company", image: "WFC@2x.png" },
    { symbol: "NIO", name: "NIO Inc.", image: "NIO@2x.png" },
    { symbol: "C", name: "Citigroup Inc.", image: "C@2x.png" },
    { symbol: "VALE", name: "Vale S.A.", image: "VALE@2x.png" },
    { symbol: "NOK", name: "Nokia Corporation", image: "NOK@2x.png" },
    { symbol: "XOM", name: "Exxon Mobil Corporation", image: "XOM@2x.png" },
    { symbol: "TSLA", name: "Tesla, Inc.", image: "TSLA@2x.png" },
    { symbol: "KO", name: "The Coca-Cola Company", image: "KO@2x.png" },
    { symbol: "BA", name: "The Boeing Company", image: "BA@2x.png" },
    { symbol: "M", name: "Macy's, Inc.", image: "M@2x.png" },
    { symbol: "INTC", name: "Intel Corporation", image: "INTC@2x.png" },
    { symbol: "SNAP", name: "Snap Inc.", image: "SNAP@2x.png" },
    { symbol: "GM", name: "General Motors Company", image: "GM@2x.png" },
    { symbol: "JPM", name: "JPMorgan Chase & Co.", image: "JPM@2x.png" },
    { symbol: "RIG", name: "Transocean Ltd.", image: "RIG@2x.png" },
    { symbol: "DIS", name: "The Walt Disney Company", image: "DIS@2x.png" },
    { symbol: "NVDA", name: "NVIDIA Corporation", image: "NVDA@2x.png" },
    { symbol: "AAL", name: "American Airlines Group Inc.", image: "AAL@2x.png" },
    { symbol: "FB", name: "Meta Platforms, Inc.", image: "FB@2x.png" },
    { symbol: "UBER", name: "Uber Technologies, Inc.", image: "UBER@2x.png" }
    // { symbol: "TWTR", name: "Twitter, Inc.", image: "TWTR@2x.png" },
    // { symbol: "MU", name: "Micron Technology, Inc.", image: "MU@2x.png" },
    // { symbol: "DAL", name: "Delta Air Lines, Inc.", image: "DAL@2x.png" },
    // { symbol: "MRNA", name: "Moderna, Inc.", image: "MRNA@2x.png" },
    // { symbol: "KOSS", name: "Koss Corporation", image: "KOSS@2x.png" },
    // { symbol: "BB", name: "BlackBerry Limited", image: "BB@2x.png" },
    // { symbol: "AMZN", name: "Amazon.com, Inc.", image: "AMZN@2x.png" },
    // { symbol: "GME", name: "GameStop Corp.", image: "GME@2x.png" },
    // { symbol: "PLTR", name: "Palantir Technologies Inc.", image: "PLTR@2x.png" },
    // { symbol: "ZNGA", name: "Zynga Inc.", image: "ZNGA@2x.png" },
    // { symbol: "SPCE", name: "Virgin Galactic Holdings, Inc.", image: "SPCE@2x.png" }
  ];

  export default stocks;