const commoditySymbols = [
    { name: "Crude Oil", symbol: "WTI", image: '17nasdaq-logo-200.png' },
    { name: "Crude Oil Brent", symbol: "BRENT", image: '17nasdaq-logo-200.png' },
    { name: "Natural Gas", symbol: "NATURAL_GAS", image: '17nasdaq-logo-200.png' },
    { name: "Copper", symbol: "COPPER", image: '17nasdaq-logo-200.png' },
    { name: "Aluminum", symbol: "ALUMINIUM", image: '17nasdaq-logo-200.png' },
    { name: "Wheat", symbol: "WHEAT", image: '17nasdaq-logo-200.png' },
    { name: "Corn", symbol: "CORN", image: '17nasdaq-logo-200.png' },
    { name: "Cotton", symbol: "COTTON", image: '17nasdaq-logo-200.png' },
    { name: "Sugar", symbol: "SUGAR", image: '17nasdaq-logo-200.png' },
    { name: "Coffee", symbol: "COFFEE", image: '17nasdaq-logo-200.png' },
    { name: "Lithium", symbol: "LITHIUM", image: '17nasdaq-logo-200.png' },
    { name: "Platinum", symbol: "PLATINUM", image: '17nasdaq-logo-200.png' },
    // Newly added commodities
    { name: "Gold", symbol: "GOLD", image: '17nasdaq-logo-200.png' },
    { name: "Nickel", symbol: "NICKEL", image: '17nasdaq-logo-200.png' },
    { name: "Ethanol", symbol: "ETHANOL", image: '17nasdaq-logo-200.png' },
    { name: "Palladium", symbol: "PALLADIUM", image: '17nasdaq-logo-200.png' },
    { name: "Silver", symbol: "SILVER", image: '17nasdaq-logo-200.png' },
    { name: "Heating Oil", symbol: "HEATING_OIL", image: '17nasdaq-logo-200.png' },
    { name: "Coal", symbol: "COAL", image: '17nasdaq-logo-200.png' },
    { name: "RBOB Gasoline", symbol: "RBOB_GASOLINE", image: '17nasdaq-logo-200.png' },
    { name: "Uranium", symbol: "URANIUM", image: '17nasdaq-logo-200.png' },
    { name: "Lead", symbol: "LEAD", image: '17nasdaq-logo-200.png' },
    { name: "Iron Ore", symbol: "IRON_ORE", image: '17nasdaq-logo-200.png' },
    { name: "Lean Hog", symbol: "LEAN_HOG", image: '17nasdaq-logo-200.png' },
    { name: "Oats", symbol: "OATS", image: '17nasdaq-logo-200.png' },
    { name: "Lumber", symbol: "LUMBER", image: '17nasdaq-logo-200.png' },
    { name: "Cocoa", symbol: "COCOA", image: '17nasdaq-logo-200.png' },
    { name: "Live Cattle", symbol: "LIVE_CATTLE", image: '17nasdaq-logo-200.png' },
    { name: "Feeder Cattle", symbol: "FEEDER_CATTLE", image: '17nasdaq-logo-200.png' },
    { name: "Milk", symbol: "MILK", image: '17nasdaq-logo-200.png' },
    { name: "Orange Juice", symbol: "ORANGE_JUICE", image: '17nasdaq-logo-200.png' },
    { name: "Palm Oil", symbol: "PALM_OIL", image: '17nasdaq-logo-200.png' },
    { name: "Rapeseed", symbol: "RAPESEED", image: '17nasdaq-logo-200.png' },
    { name: "Rice", symbol: "RICE", image: '17nasdaq-logo-200.png' },
    { name: "Zinc", symbol: "ZINC", image: '17nasdaq-logo-200.png' },
    { name: "Soybean Meal", symbol: "SOYBEAN_MEAL", image: '17nasdaq-logo-200.png' },
    { name: "Soybeans", symbol: "SOYBEANS", image: '17nasdaq-logo-200.png' },
    { name: "Soybean Oil", symbol: "SOYBEAN_OIL", image: '17nasdaq-logo-200.png' },
    { name: "Tin", symbol: "TIN", image: '17nasdaq-logo-200.png' }
];

export default commoditySymbols;